name: recsys_app
version: '3.8'
services:
  ml-app:
    image: localhost/recsys_dvc:v1.0.1
    networks:
      - recommender-system_default
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    restart: on-failure:5

networks:
  recommender-system_default:
    external: true