stages:
  preprocess:
    cmd: uv run python src/data/preprocessing.py
    deps:
      - src/data/preprocessing.py
      - data/raw
    params:
      - preprocess.train_size
      - preprocess.random_state
    outs:
      - data/processed/train_data.data
      - data/processed/test_data.data

  train:
    cmd: uv run python src/models/train.py
    deps:
      - src/models/train.py
      - data/processed/train_data.data
    params:
      - train.n_factors
      - train.n_epochs
      - train.lr_all
      - train.reg_all
    outs:
      - models/model.pkl
    metrics:
      - train_metrics.json:
          cache: false
          
  # batch_predict:
  #   cmd: uv run python src/models/predict.py
  #   deps:
  #     - src/models/predict.py
  #     - models/model.pkl
  #     - data/processed/trainset.pkl
    
  # evaluate:
  #   cmd: uv run python src/models/evaluate.py
  #   deps:
  #     - src/models/evaluate.py
  #     - models/model.pkl
  #     - data/processed/test.csv
  #   metrics:
  #     - results/metrics.json:
  #         cache: false
  #   plots:
  #     - results/confusion_matrix.json:
  #         cache: false